version: '3.8'

networks:
  internal_network:
    internal: true
  external_network:
    driver: bridge

services:
  # jenkins - for workflow manager
  jenkins:
    image: bitnami/jenkins:2.462.3
    user: root
    container_name: ape-jenkins
    platform: linux/amd64
    networks:
      - internal_network
      - external_network
    ports:
      - target: 8080
        published: 9900
        protocol: tcp
    volumes:
      - ~/:/var/jenkins_home # -v $HOME/mcmp/oss/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker # -v $(which docker):/usr/bin/docker
    environment:
      JENKINS_USERNAME: admin
      JENKINS_PASSWORD: 123456 # Please CHANGE ME
      JENKINS_PLUGINS: >-
        workflow-api,
        swarm,
        authorize-project,
        antisamy-markup-formatter,
        pipeline-github-lib,
        pipeline-rest-api,
        git,
        github-branch-source,
        gradle,
        pipeline-model-definition,
        pipeline-build-step,
        workflow-aggregator,
        matrix-project,
        email-ext,
        durable-task,
        checks-api,
        build-timeout,
        timestamper,
        ws-cleanup,
        ssh-slaves,
        ssh-agent,
        publish-over-ssh
    healthcheck: # for application-manager
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s

  # sonatype nexus - for application manager
  sonatype-nexus:
    image: sonatype/nexus3:latest
    container_name: nexus-repository
    platform: linux/amd64
    networks:
      - internal_network
      - external_network
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
      - target: 5500 # container-repository
        published: 5500
        protocol: tcp
      - target: 5600 # container-repository
        published: 5600
        protocol: tcp
    volumes:
      - ~/:/nexus-data/blobs/
    environment: 
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
      NEXUS_SECURITY_INITIAL_PASSWORD: 123456 # Please CHANGE ME
    healthcheck: # for application-manager
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s

  # application-manager
  mc-application-manager:
    image: cloudbaristaorg/mc-application-manager:edge
    container_name: application-manager
    privileged: true  # Docker-in-Docker를 위한 privileged 모드
    networks:
      - external_network
    ports:
      - target: 18084
        published: 18084
        protocol: tcp
    volumes:
      - ./db/application:/db/application
      - dind-storage:/var/lib/docker  # DinD용 Docker 데이터 볼륨
      - /var/run:/var/run  # DinD 소켓용
    environment:
      - DDL_AUTO=update     # create-drop or update
      - DB_USER=application # Please CHANGE ME
      - DB_PASS=application!23 # Please CHANGE ME
      - SQL_DATA_INIT=never # or never or always
      - TUMBLEBUG_URL=mc-infra-manager
      - TUMBLEBUG_PORT=1323
      - TUMBLEBUG_ID=default
      - TUMBLEBUG_PASSWORD=default
    healthcheck: # for cb-application-manager
      test: ["CMD", "nc", "-vz", "localhost", "1324"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  dind-storage:
