server:
  port: 18085

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

spring:
  application:
    name: appManager 

  # datasource:
  #   hikari:
  #     username: ${DB_USER_NAME}
  #     password: ${DB_PWD}
  #     driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #     jdbc-url: "jdbc:mariadb://${DB_URL:localhost:3306}/mcmp?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false"
  #     idle-timeout: 250 
  #     max-lifetime: 250 
  datasource:
    hikari:
      username: ${DB_ID:root}
      password: ${DB_PW:roqkftpsxj12#$}
      driver-class-name: ${DB_DRIVER:org.sqlite.JDBC} #net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url:  ${DB:sqlite:m-cmp.db}
      idle-timeout: 250
      max-lifetime: 250


management:
  endpoints:
    enabled-by-default: false 
    web:
      exposure:
        include: info, health
      base-path: /mmpact
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

springdoc:
  swagger-ui:
    groups-order: desc               
    operations-sorter: method        
  show-actuator: false               

## ArgoCd
argocd:
  project:
    name: m-cmp

aes:
  key: fb1755281b0ca6184a0ee644e6477ee7


gitlab:
  deploy:
    yaml:
      path: m-cmp/k8s
      filename: deploy.yaml
